### ISSUE TITLE
pyquic circular import

### ISSUE THREAD

**Issue by shahrozeabbas** [cantinilab/Circe#3]
Hello - apologize for the back to back issues open. 

I am using a `conda` environment with pip to install `circe` with `pip install circe-py`. I know you mentioned a `pyquic` error if the repo is cloned, however when I import the package, I receive the following error. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abbass2/.local/lib/python3.9/site-packages/circe/__init__.py", line 1, in <module>
    from .circe import extract_atac_links, \
  File "/home/abbass2/.local/lib/python3.9/site-packages/circe/circe.py", line 6, in <module>
    from . import quic_graph_lasso
  File "/home/abbass2/.local/lib/python3.9/site-packages/circe/quic_graph_lasso.py", line 18, in <module>
    from . import pyquic
ImportError: cannot import name 'pyquic' from partially initialized module 'circe' (most likely due to a circular import) (/home/abbass2/.local/lib/python3.9/site-packages/circe/__init__.py)
```

Any ideas what could be going wrong? I assumed with a `conda` environment, things would be as smooth as possible.

**Comment by r-trimbour** [comment]
Hi Shahroze,

1. Regarding the error I mentioned a few months ago:
if you are inside the repo, the line `from . import pyquic` will try to load the folder called `circe/pyquic/`.

It usually works fine with python-only packages, but since this dependency needs to be compiled, it cannot be imported this way and causes the error.

Normally, if you try to `import Circe` after just `cd ..` or changing directory, it should then work.

2. If it doesn't solve your issue, you can give a try to:
```
pip uninstall circe
pip install -e circe_repo
```

3. If both don't solve your issue, could you indicate to me your version of the package with `pip show circe` ?

_PS:  I tried to modify Circe for your other issue, answering you really soon_ :)

Rémi

**Comment by shahrozeabbas** [comment]
Ahh yes, this does sound familiar. WIll update as soon as I try again with these approaches.

**Comment by shahrozeabbas** [comment]
Seems to not be a problem after getting it to install in a `conda` environment.
