### ISSUE TITLE
Please add version tags to the github repo

### ISSUE THREAD

**Issue by PetrKralCZ** [cantinilab/Circe#4]
I am an [EasyBuild](https://easybuild.io/) maintainer and for us to be able to install for example `CIRCE-0.3.3`, we patch the `build.py` script like this:
```bash
sed -i 's/lapack/flexiblas/g' build.py
```
We have to use the source from Github for that since the Pypi tarball does not contain this file. The only problem is we are not sure commit corresponds to the version `0.3.3`.
Could you please tag the commits?

**Comment by r-trimbour** [comment]
Hi,
Thanks for your feedback, I will look into commit tags and try to do so from now on. :)
Let me now or don't hesitate to do pull request if any code modification could make your work simpler or the installation more standard.

Btw I currently don't upload wheels currently, I'm discovering how to (and struggling) to build a universal/many-linux one, because of this `lapack` depency... Are you currently building wheels for it ? If yes, is it a public code that I could use to push directly a wheel on pypi ?
Thanks a lot !

Side note: Please disregard the version `0.3.3`, I built it with poetry that didn't use `setup.py`.
I deleted the` build.py` file and switched from poetry to `python -m build` to reduce build errors, it should be more stable from 0.3.4.

Rémi
